# Generated by Django 5.2.17 on 2026-09-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_id', models.CharField(max_length=50)),
                ('exchange_segment', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=100)),
                ('timeframe', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=4, max_digits=15)),
                ('high', models.DecimalField(decimal_places=4, max_digits=15)),
                ('low', models.DecimalField(decimal_places=4, max_digits=15)),
                ('close', models.DecimalField(decimal_places=4, max_digits=15)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('open_interest', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'timeframe', 'timestamp'], name='market_data_symbol_41f8d5_idx')],
                'constraints': [models.UniqueConstraint(fields=('security_id', 'timeframe', 'timestamp'), name='unique_market_candle')],
            },
        ),
    ]
