# Generated by Django 5.2.17 on 2026-09-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candle',
            options={'ordering': ['timestamp']},
        ),
    ]
