# Generated by Django 5.2.17 on 2026-09-18 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('initial_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('final_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('return_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('win_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_drawdown', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_trades', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategies.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BacktestTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('side', models.CharField(max_length=10)),
                ('entry_time', models.DateTimeField()),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('exit_time', models.DateTimeField(null=True)),
                ('exit_price', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('quantity', models.IntegerField()),
                ('pnl', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('exit_reason', models.CharField(blank=True, max_length=50)),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='backtesting.backtest')),
            ],
        ),
    ]
