# Generated by Django 5.2.17 on 2026-09-18 14:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0001_initial'),
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backtest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='backtesttrade',
            options={'ordering': ['entry_time']},
        ),
        migrations.AddField(
            model_name='backtest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='backtesttrade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backtest',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='max_drawdown',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='return_percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to='strategies.strategy'),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='total_trades',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='win_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='backtesttrade',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='backtesttrade',
            name='exit_reason',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='backtesttrade',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backtesttrade',
            name='pnl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='backtesttrade',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='backtesttrade',
            name='side',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10),
        ),
    ]
