# Generated by Django 5.2.17 on 2026-09-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='timeframe',
            field=models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('25m', '25 Minutes'), ('1h', '1 Hour'), ('1d', '1 Day (EOD)')], max_length=10),
        ),
    ]
