# Generated by Django 5.2.17 on 2026-09-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_segment', models.CharField(db_index=True, max_length=30)),
                ('security_id', models.CharField(db_index=True, max_length=50)),
                ('trading_symbol', models.CharField(db_index=True, max_length=100)),
                ('symbol', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('instrument_type', models.CharField(choices=[('EQUITY', 'Equity Stock'), ('INDEX', 'Index'), ('FUTIDX', 'Index Future'), ('OPTIDX', 'Index Option'), ('FUTSTK', 'Stock Future'), ('OPTSTK', 'Stock Option')], db_index=True, default='EQUITY', max_length=30)),
                ('expiry', models.DateField(blank=True, db_index=True, null=True)),
                ('strike', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('option_type', models.CharField(blank=True, choices=[('CE', 'Call Option'), ('PE', 'Put Option')], max_length=10, null=True)),
                ('lot_size', models.IntegerField(default=1)),
                ('tick_size', models.DecimalField(decimal_places=4, default=0.05, max_digits=8)),
                ('source', models.CharField(default='DHAN', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol', 'trading_symbol'],
                'indexes': [models.Index(fields=['symbol', 'exchange_segment'], name='instruments_symbol_c1bd88_idx'), models.Index(fields=['instrument_type', 'is_active'], name='instruments_instrum_35c5e1_idx'), models.Index(fields=['trading_symbol'], name='instruments_trading_828968_idx')],
                'constraints': [models.UniqueConstraint(fields=('exchange_segment', 'security_id'), name='unique_exchange_security_id')],
            },
        ),
    ]
